package com.ccee.projetotestejava.exception;

/**
 * Checked exception lançada na classe 'FuncionarioDao' 
 * quando ocorre um erro de conexão ao Banco de Dados.
 * 
 * @author bruno.minozzi
 * @since 27/10/2019
 */
public class FuncionarioDaoException extends Exception {

	private static final long serialVersionUID = 1L;

	public FuncionarioDaoException() {
		super();
	}

	public FuncionarioDaoException(String message, Throwable cause, boolean enableSuppression,
			boolean writableStackTrace) {
		super(message, cause, enableSuppression, writableStackTrace);
	}

	public FuncionarioDaoException(String message, Throwable cause) {
		super(message, cause);
	}

	public FuncionarioDaoException(String message) {
		super(message);
	}

	public FuncionarioDaoException(Throwable cause) {
		super(cause);
	}
}